[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# remappings = [
#     "@chainlink=lib/foundry-chainlink-toolkit",
#     "@chainlink-ccip/=lib/chainlink-ccip/chains/evm/contracts",
#     "@chainlink/contracts=lib/chainlink-ccip/chains/evm/contracts",
#     "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
# ]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
eth-rpc-url = "https://eth-sepolia.g.alchemy.com/v2/RV2x_tBqLkqNUuIXb7NfhmdL38Rxqj6Y"
chain_id = 11155111
