[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink=lib/foundry-chainlink-toolkit/src"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
eth-rpc-url = "https://eth-sepolia.g.alchemy.com/v2/RV2x_tBqLkqNUuIXb7NfhmdL38Rxqj6Y"
chain_id = 11155111
